apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/webapp-prebuilt.yml -o webapp-prebuilt
    kompose.version: 1.20.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose/webapp-prebuilt.yml -o webapp-prebuilt
        kompose.version: 1.20.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: namenode
    spec:
      containers:
      - env:
        - name: ADD_USERS
          value: spark,hbase
        - name: DFS_DEFAULT
          value: hdfs://namenode:8020
        - name: DFS_NAMENODES
          value: rpc://namenode:8020,http://namenode:9870,https://namenode:9871
        - name: NAME_DIRS
          value: /home/hadoop/name
        - name: ROLE
          value: namenode
        image: registry.gitlab.com/rychly-edu/docker/docker-hdfs:3.1.3
        name: namenode
        ports:
        - containerPort: 9870
        resources: {}
        volumeMounts:
        - mountPath: /home/hadoop/name
          name: namenode-claim0
      restartPolicy: Always
      volumes:
      - name: namenode-claim0
        persistentVolumeClaim:
          claimName: namenode-claim0
status: {}
